export default {
  palette: {
    themeDarker: "#470a04",
    themeDark: "#7d0c00",
    themeDarkAlt: "#6d6c6f",
    themePrimary: "#7d0c00",
    themeSecondary: "#6e8f8f",
    themeTertiary: "#d1c0b2",
    themeLight: "#7d0c00",
    themeLighter: "#7d0c00",
    themeLighterAlt: "#acd6d6",
    black: "#1d1d1d",
    blackTranslucent40: "rgba(0,0,0,.4)",
    neutralDark: "#272727",
    neutralPrimary: "#333333",
    neutralPrimaryAlt: "#6d6c6f",
    neutralSecondary: "#c2a189",
    neutralSecondaryAlt: "#8a8886",
    neutralTertiary: "#c6c6c8",
    neutralTertiaryAlt: "#c6c6c8",
    neutralQuaternary: "#d0d0d0",
    neutralQuaternaryAlt: "#dadada",
    neutralLight: "#eaeaea",
    neutralLighter: "#f4f4f4",
    neutralLighterAlt: "#f8f8f8",
    accent: "#6e8f8f",
    white: "#ffffff",
    whiteTranslucent40: "rgba(255, 255, 255, 0.40)",
    yellowDark: "#d29200",
    yellow: "#ffb900",
    yellowLight: "#fff100",
    orange: "#d83b01",
    orangeLight: "#ea4300",
    orangeLighter: "#ff8c00",
    redDark: "#a4262c",
    red: "#e81123",
    magentaDark: "#5c005c",
    magenta: "#b4009e",
    magentaLight: "#e3008c",
    purpleDark: "#32145a",
    purple: "#5c2d91",
    purpleLight: "#b4a0ff",
    blueDark: "#002050",
    blueMid: "#00188f",
    blue: "#0078d4",
    blueLight: "#00bcf2",
    tealDark: "#004b50",
    teal: "#008272",
    tealLight: "#00b294",
    greenDark: "#004b1c",
    green: "#107c10",
    greenLight: "#bad80a",
    primaryText: "#333333",
    bodyText: "#333333",
    disabledBackground: "#f4f4f4",
    disabledText: "#c8c8c8",
    bodyBackground: "#ffffff",
    primaryBackground: "#ffffff",
    HyperlinkActive: "#470a04",
    CommandLinksPressed: "#470a04",
    NavigationPressed: "#470a04",
    EmphasisHoverBorder: "#470a04",
    TopBarPressedText: "#470a04",
    HeaderNavigationPressedText: "#470a04",
    Hyperlinkfollowed: "#470a04",
    EmphasisHoverBackground: "#7d0c00",
    EmphasisBorder: "#7d0c00",
    AccentText: "#7d0c00",
    CommandLinksHover: "#7d0c00",
    RowAccent: "#7d0c00",
    NavigationAccent: "#7d0c00",
    NavigationHover: "#7d0c00",
    EmphasisBackground: "#7d0c00",
    HeaderNavigationHoverText: "#7d0c00",
    HeaderNavigationSelectedText: "#7d0c00",
    SuiteBarBackground: "#7d0c00",
    Hyperlink: "#7d0c00",
    ContentAccent1: "#7d0c00",
    AccentLines: "#6e8f8f",
    HeaderAccentLines: "#6e8f8f",
    ButtonPressedBorder: "#6e8f8f",
    SuiteBarHoverBackground: "#d1c0b2",
    StrongLines: "#7d0c00",
    HeaderStrongLines: "#7d0c00",
    SuiteBarHoverText: "#7d0c00",
    ButtonPressedBackground: "#7d0c00",
    ButtonHoverBorder: "#7d0c00",
    ButtonHoverBackground: "#7d0c00",
    SelectionBackground: "rgba(125, 12, 0, 0.50)",
    HoverBackground: "rgba(125, 12, 0, 0.50)",
    NavigationHoverBackground: "rgba(125, 12, 0, 0.50)",
    PageBackground: "#ffffff",
    EmphasisText: "#ffffff",
    SuiteBarText: "#ffffff",
    TileText: "#ffffff",
    BackgroundOverlay: "rgba(255, 255, 255, 0.85)",
    HeaderBackground: "rgba(255, 255, 255, 0.85)",
    FooterBackground: "rgba(255, 255, 255, 0.85)",
    DisabledBackground: "#f8f8f8",
    HeaderDisabledBackground: "#f8f8f8",
    ButtonBackground: "#f8f8f8",
    ButtonDisabledBackground: "#f8f8f8",
    SubtleEmphasisBackground: "#f4f4f4",
    DialogBorder: "#f4f4f4",
    NavigationSelectedBackground: "rgba(234, 234, 234, 0.78)",
    TopBarBackground: "rgba(234, 234, 234, 0.78)",
    DisabledLines: "#eaeaea",
    HeaderDisabledLines: "#eaeaea",
    ButtonDisabledBorder: "#eaeaea",
    SuiteBarDisabledText: "#eaeaea",
    SubtleLines: "#c6c6c8",
    HeaderSubtleLines: "#c6c6c8",
    ButtonGlyphDisabled: "#c6c6c8",
    DisabledText: "#c6c6c8",
    CommandLinksDisabled: "#c6c6c8",
    HeaderDisableText: "#c6c6c8",
    ButtonDisabledText: "#c6c6c8",
    Lines: "#c6c6c8",
    HeaderLines: "#c6c6c8",
    ButtonBorder: "#c6c6c8",
    CommandLinks: "#c2a189",
    Navigation: "#c2a189",
    SubtleEmphasisText: "#c2a189",
    TopBarText: "#c2a189",
    HeaderNavigationText: "#c2a189",
    ButtonGlyph: "#c2a189",
    BodyText: "#333333",
    WebPartHeading: "#333333",
    HeaderText: "#333333",
    ButtonText: "#333333",
    ButtonGlyphActive: "#333333",
    TopBarHoverText: "#333333",
    StrongBodyText: "#272727",
    SiteTitle: "#272727",
    CommandLinksSecondary: "#272727",
    SubtleEmphasisCommandLinks: "#272727",
    HeaderSiteTitle: "#272727",
    TileBackgroundOverlay: "rgba(29, 29, 29, 0.50)",
    ContentAccent2: "#00485b",
    ContentAccent3: "#288054",
    ContentAccent4: "#767956",
    ContentAccent5: "#ed0033",
    ContentAccent6: "#682a7a",
    backgroundOverlay: "rgba(255, 255, 255, 0.85)",
    themeAccent: "#7d0c00",
    themeAccentTranslucent10: "rgba(125, 12, 0, 0.10)",
    suiteBarBackground: "#7d0c00",
    suiteBarText: "#ffffff",
    suiteBarDisabledText: "#eaeaea",
    topBarBackground: "rgba(234, 234, 234, 0.78)",
    topBarText: "#c2a189",
    topBarHoverText: "#333333",
    dialogBorder: "#f4f4f4",
  },
  fonts: {
    tiny: {
      fontFamily:
        "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
      MozOsxFontSmoothing: "grayscale",
      WebkitFontSmoothing: "antialiased",
      fontSize: 10,
      fontWeight: 600,
    },
    xSmall: {
      fontFamily:
        "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
      MozOsxFontSmoothing: "grayscale",
      WebkitFontSmoothing: "antialiased",
      fontSize: 11,
      fontWeight: 400,
    },
    small: {
      fontFamily:
        "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
      MozOsxFontSmoothing: "grayscale",
      WebkitFontSmoothing: "antialiased",
      fontSize: 12,
      fontWeight: 400,
    },
    smallPlus: {
      fontFamily:
        "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
      MozOsxFontSmoothing: "grayscale",
      WebkitFontSmoothing: "antialiased",
      fontSize: 13,
      fontWeight: 400,
    },
    medium: {
      fontFamily:
        "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
      MozOsxFontSmoothing: "grayscale",
      WebkitFontSmoothing: "antialiased",
      fontSize: 14,
      fontWeight: 400,
    },
    mediumPlus: {
      fontFamily:
        "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
      MozOsxFontSmoothing: "grayscale",
      WebkitFontSmoothing: "antialiased",
      fontSize: 15,
      fontWeight: 400,
    },
    large: {
      fontFamily:
        "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
      MozOsxFontSmoothing: "grayscale",
      WebkitFontSmoothing: "antialiased",
      fontSize: 17,
      fontWeight: 300,
    },
    xLarge: {
      fontFamily:
        "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
      MozOsxFontSmoothing: "grayscale",
      WebkitFontSmoothing: "antialiased",
      fontSize: 21,
      fontWeight: 100,
    },
    xLargePlus: {
      fontFamily:
        "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
      MozOsxFontSmoothing: "grayscale",
      WebkitFontSmoothing: "antialiased",
      fontSize: 21,
      fontWeight: 100,
    },
    xxLarge: {
      fontFamily:
        "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
      MozOsxFontSmoothing: "grayscale",
      WebkitFontSmoothing: "antialiased",
      fontSize: 28,
      fontWeight: 100,
    },
    xxLargePlus: {
      fontFamily:
        "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
      MozOsxFontSmoothing: "grayscale",
      WebkitFontSmoothing: "antialiased",
      fontSize: 28,
      fontWeight: 100,
    },
    superLarge: {
      fontFamily:
        "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
      MozOsxFontSmoothing: "grayscale",
      WebkitFontSmoothing: "antialiased",
      fontSize: 42,
      fontWeight: 100,
    },
    mega: {
      fontFamily:
        "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
      MozOsxFontSmoothing: "grayscale",
      WebkitFontSmoothing: "antialiased",
      fontSize: 72,
      fontWeight: 100,
    },
  },
  semanticColors: {
    bodyBackground: "#ffffff",
    bodyBackgroundHovered: "#f4f4f4",
    bodyBackgroundChecked: "#eaeaea",
    bodyStandoutBackground: "#f8f8f8",
    bodyFrameBackground: "#ffffff",
    bodyFrameDivider: "#eaeaea",
    bodyText: "#333333",
    bodyTextChecked: "#1d1d1d",
    bodySubtext: "#c2a189",
    bodyDivider: "#eaeaea",
    disabledBackground: "#f4f4f4",
    disabledText: "#c6c6c8",
    disabledSubtext: "#d0d0d0",
    disabledBodyText: "#c6c6c8",
    disabledBodySubtext: "#c6c6c8",
    disabledBorder: "#c6c6c8",
    focusBorder: "#c2a189",
    variantBorder: "#eaeaea",
    variantBorderHovered: "#c6c6c8",
    defaultStateBackground: "#f8f8f8",
    errorText: "#a4262c",
    warningText: "#333333",
    successText: "#107C10",
    errorBackground: "rgba(232, 17, 35, .2)",
    blockingBackground: "rgba(234, 67, 0, .2)",
    warningBackground: "rgba(255, 185, 0, .2)",
    warningHighlight: "#ffb900",
    successBackground: "rgba(186, 216, 10, .2)",
    inputBorder: "#c6c6c8",
    inputBorderHovered: "#333333",
    inputBackground: "#ffffff",
    inputBackgroundChecked: "#7d0c00",
    inputBackgroundCheckedHovered: "#6d6c6f",
    inputPlaceholderBackgroundChecked: "#7d0c00",
    inputForegroundChecked: "#ffffff",
    inputIcon: "#7d0c00",
    inputIconHovered: "#7d0c00",
    inputIconDisabled: "#c6c6c8",
    inputFocusBorderAlt: "#7d0c00",
    smallInputBorder: "#c2a189",
    inputText: "#333333",
    inputTextHovered: "#272727",
    inputPlaceholderText: "#c2a189",
    buttonBackground: "#f4f4f4",
    buttonBackgroundChecked: "#c6c6c8",
    buttonBackgroundHovered: "#eaeaea",
    buttonBackgroundCheckedHovered: "#eaeaea",
    buttonBackgroundPressed: "#eaeaea",
    buttonBackgroundDisabled: "#f4f4f4",
    buttonBorder: "transparent",
    buttonText: "#333333",
    buttonTextHovered: "#272727",
    buttonTextChecked: "#272727",
    buttonTextCheckedHovered: "#1d1d1d",
    buttonTextPressed: "#272727",
    buttonTextDisabled: "#c6c6c8",
    buttonBorderDisabled: "transparent",
    primaryButtonBackground: "#7d0c00",
    primaryButtonBackgroundHovered: "#6d6c6f",
    primaryButtonBackgroundPressed: "#7d0c00",
    primaryButtonBackgroundDisabled: "#f4f4f4",
    primaryButtonBorder: "transparent",
    primaryButtonText: "#ffffff",
    primaryButtonTextHovered: "#ffffff",
    primaryButtonTextPressed: "#ffffff",
    primaryButtonTextDisabled: "#d0d0d0",
    accentButtonBackground: "#6e8f8f",
    accentButtonText: "#ffffff",
    menuBackground: "#ffffff",
    menuDivider: "#c6c6c8",
    menuIcon: "#7d0c00",
    menuHeader: "#7d0c00",
    menuItemBackgroundHovered: "#f4f4f4",
    menuItemBackgroundPressed: "#eaeaea",
    menuItemText: "#333333",
    menuItemTextHovered: "#272727",
    listBackground: "#ffffff",
    listText: "#333333",
    listItemBackgroundHovered: "#f4f4f4",
    listItemBackgroundChecked: "#eaeaea",
    listItemBackgroundCheckedHovered: "#dadada",
    listHeaderBackgroundHovered: "#f4f4f4",
    listHeaderBackgroundPressed: "#eaeaea",
    actionLink: "#333333",
    actionLinkHovered: "#272727",
    link: "#7d0c00",
    linkHovered: "#470a04",
    listTextColor: "#333333",
    menuItemBackgroundChecked: "#eaeaea",
  },
  isInverted: false,
  disableGlobalClassNames: false,
  spacing: { s2: "4px", s1: "8px", m: "16px", l1: "20px", l2: "32px" },
  effects: {
    elevation4: "0 1.6px 3.6px 0 rgba(0, 0, 0, 0.132), 0 0.3px 0.9px 0 rgba(0, 0, 0, 0.108)",
    elevation8: "0 3.2px 7.2px 0 rgba(0, 0, 0, 0.132), 0 0.6px 1.8px 0 rgba(0, 0, 0, 0.108)",
    elevation16: "0 6.4px 14.4px 0 rgba(0, 0, 0, 0.132), 0 1.2px 3.6px 0 rgba(0, 0, 0, 0.108)",
    elevation64: "0 25.6px 57.6px 0 rgba(0, 0, 0, 0.22), 0 4.8px 14.4px 0 rgba(0, 0, 0, 0.18)",
    roundedCorner2: "2px",
  },
};
